### ISSUE TITLE
trouble building

### ISSUE THREAD

**Issue by bwheel12** [statgen/popscle#26]
when trying to build this on my machine I get the following message when I run make: 

CMakeFiles/popscle.dir/filter.cpp.o: In function `filters_set_ref_string(_filter_t*, bcf1_t*, _token_t*)':
filter.cpp:(.text+0x1696): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
CMakeFiles/popscle.dir/filter.cpp.o: In function `filters_set_genotype_string(_filter_t*, bcf1_t*, _token_t*)':
filter.cpp:(.text+0x1bcb): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
filter.cpp:(.text+0x1c46): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
filter.cpp:(.text+0x218e): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
filter.cpp:(.text+0x21b3): undefined reference to `ks_resize2(kstring_t*, unsigned long)'
CMakeFiles/popscle.dir/filter.cpp.o:filter.cpp:(.text+0x21db): more undefined references to `ks_resize2(kstring_t*, unsigned long)' follow
collect2: error: ld returned 1 exit status
CMakeFiles/popscle.dir/build.make:932: recipe for target '../bin/popscle' failed
make[2]: *** [../bin/popscle] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/popscle.dir/all' failed
make[1]: *** [CMakeFiles/popscle.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ytang0831** [comment]
Me too, did you find the solution? @bwheel12

**Comment by ytang0831** [comment]
@bwheel12 Hi, I think your htslib version is 1.9. After upgrade to 1.10, issue resolved !
It seems that the latest version of htslib will also cause problems, and htlib-1.10 should be the most suitable version.

If you have solved this problem, this comment can also help others who use htslib-1.9。
