### ISSUE TITLE
Compiling error with gtf_interval_tree.h

### ISSUE THREAD

**Issue by dfermin** [statgen/popscle#45]
Hello.

I just cloned the latest repo from GitHub and I'm trying to compile it on RHEL 8.
Running make I get the following error: 

```
[ 30%] Building CXX object CMakeFiles/popscle.dir/cmd_cram_freemux2.cpp.o
[ 33%] Building CXX object CMakeFiles/popscle.dir/cmd_plp_make_dge_matrix.cpp.o
In file included from /app/tmp/popscle.git/gtf.h:30:0,
                 from /app/tmp/popscle.git/cmd_plp_make_dge_matrix.cpp:2:
/app/tmp/popscle.git/gtf_interval_tree.h:87:26: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     ~gtfIntervalTree() = default;
                          ^
/app/tmp/popscle.git/gtf_interval_tree.h:89:5: error: ‘unique_ptr’ in namespace ‘std’ does not name a type
     std::unique_ptr<gtfIntervalTree> clone() const {
     ^
/app/tmp/popscle.git/gtf_interval_tree.h:100:47: error: expected ‘,’ or ‘...’ before ‘&&’ token
     gtfIntervalTree& operator=(gtfIntervalTree&&) = default;

/app/tmp/popscle.git/gtf_interval_tree.h:100:53: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     gtfIntervalTree& operator=(gtfIntervalTree&&) = default;
                                                     ^
/app/tmp/popscle.git/gtf_interval_tree.h:101:36: error: expected ‘,’ or ‘...’ before ‘&&’ token
     gtfIntervalTree(gtfIntervalTree&&) = default;
                                    ^
/app/tmp/popscle.git/gtf_interval_tree.h:101:42: warning: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [enabled by default]
     gtfIntervalTree(gtfIntervalTree&&) = default;
                                          ^
/app/tmp/popscle.git/gtf_interval_tree.h:101:42: error: invalid constructor; you probably meant ‘gtfIntervalTree<Scalar, Value> (const gtfIntervalTree<Scalar, Value>&)’
/app/tmp/popscle.git/gtf_interval_tree.h:112:32: error: expected ‘,’ or ‘...’ before ‘&&’ token
             gtf_interval_vector&& ivals,
                                ^
```

The errors go on but I'm guessing I would start with these error and see what goes away after they get addressed.

Any suggestions?

**Comment by hyunminkang** [comment]
What was your g++ version and development platform?

**Comment by dfermin** [comment]
We are working on Linux (Redhat 8) 
g++ version 4.8.5

**Comment by dfermin** [comment]
Hi I just wanted to see if there was any update on this one. 
We are eager to use demuxlet from this repo.

**Comment by hyunminkang** [comment]
I suspect that upgrading g++ may work, but I cannot tell what went wrong.

What I can say is that it works with Ubuntu 18.04 with g++ 7.5.0

Hyun.
-----------------------------------------------------
Hyun Min Kang, Ph.D.
Associate Professor of Biostatistics
University of Michigan, Ann Arbor
Email : ***@***.***

**Comment by dfermin** [comment]
I was able to compile popscle when using **g++ 8.3.1** so it looks like this is the culprit. 
Thanks,
